name: template_utils
description: A sample command-line application.
version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: ^3.0.0

dependencies:
  mason: any
  collection: ^1.19.1
  path: ^1.9.1
  async: ^2.13.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

