name: use_case_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  template_utils:
#    path: ../../template_utils
    git:
      url: https://github.com/weichwaren-schmiede/flutter-clean-arch-templates.git
      path: template_utils
      ref: '93408da19bcc0832966900ab42a71a2e8f76507c'
  mason: any