name: page_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  template_utils:
    #    path: ../../template_utils
    git:
      url: https://github.com/weichwaren-schmiede/flutter-clean-arch-templates.git
      path: template_utils
      ref: '399f17f259a7439a13e1bf2ac904bc4b45096c13'
  mason: any